# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "iron_mq"
  s.version = "1.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Travis Reeder"]
  s.date = "2012-03-02"
  s.description = "Ruby client for IronMQ"
  s.email = "travis@iron.io"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
    "Rakefile",
    "VERSION.yml",
    "iron_mq.gemspec",
    "lib/iron_mq.rb",
    "lib/iron_mq/client.rb",
    "lib/iron_mq/messages.rb",
    "lib/iron_mq/queues.rb",
    "test/Gemfile",
    "test/Gemfile.lock",
    "test/long_run.rb",
    "test/long_run_worker.rb",
    "test/quick_run.rb",
    "test/schedule_abt.rb",
    "test/test_base.rb",
    "test/test_beanstalkd.rb",
    "test/test_iron_mq.rb"
  ]
  s.homepage = "http://www.iron.io"
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9")
  s.rubygems_version = "1.8.15"
  s.summary = "Ruby client for IronMQ"
  
  
  s.add_runtime_dependency "faraday"

end

